[package]
name = "nowoshire/lazyvaluebucket"
description = "An implementation of lazily evaluated token buckets in Luau."
version = "1.0.1"
license = "MIT"
authors = ["Nowoshire"]

registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Nowoshire/LazyValueBucket"

realm = "shared"
include = ["*"]

[dependencies]